### ISSUE TITLE
Testing usage peaks 

### ISSUE THREAD

**Issue by seguri** [xlucasdemelo/resilience-patterns#1]
Hi Lucas,

Thanks for your tutorials around resilience4j. Could you please help me write a test like `everybodyInTheLibrary` for a RateLimiter? I'd like to prepare 10 requests and send them all at once against the `mockWebServer`, and then check how many succeeded and how many failed.

Given this configuration:
```yaml
resilience4j:
  ratelimiter:
    instances:
      hello:
        limitForPeriod: 1
        limitRefreshPeriod: 1s
        timeoutDuration: 5s
```

and a rate limited controller:

```java
@RateLimiter(name = "hello")
@GetMapping("/hello")
String hello() {
  return "hello";
}
```

I'd like to prepare 10 requests and send them to... an `ExecutorService`? Something like:

```java
@Test
void test() {
  enqueue(NUMBER_OF_REQUESTS, "hello");
  final Runnable task = () -> get("/hello");
  final var tasks =
        Stream.continually(task).map(Executors::callable).take(NUMBER_OF_REQUESTS).toJavaList();
  Executors.newFixedThreadPool(NUMBER_OF_REQUESTS).invokeAll(tasks, 10, SECONDS);
  assertThat(events.size()).isEqualTo(NUMBER_OF_REQUESTS);
}

private ExtractableResponse<Response> get(final String path) {
  return io.restassured.RestAssured.given().get(mockWebServer.url(path).toString()).then().extract();
}
```

This is an example of something that is not working. I'm new to `vavr` and I'm struggling to find an idiomatic way to write this test. Hope you can help me.

Thanks
